library(DBI)
library(RSQLite)
library(sqldf)
#Create A new SQLite database
Labdb <- dbConnect(RSQLite::SQLite(), "lab-db.sqlite")
EMPLOYEE <- read.csv("~/Desktop/EMPLOYEE.txt")
STOCK<- read.csv("~/Desktop/STOCK_TOTAL.txt")
INVOICES<- read.csv("~/Desktop/INVOICES.txt")
SalesOrderLine <- read.csv("~/Desktop/SALES_ORDER_LINE.txt")
SALESORDER<- read.csv("~/Desktop/SALES_ORDER.txt")
Product <- read.csv("~/Desktop/PRODUCT.txt")
Customer <- read.csv("~/Desktop/CUSTOMER.txt")
EmployeePhone <- read.csv("~/Desktop/EMPLOYEE_PHONE.txt")
Department <- read.csv("~/Desktop/Department.txt")
dbWriteTable(Labdb, "EMPLOYEE", EMPLOYEE)
dbWriteTable(Labdb, "STOCK", STOCK)
dbWriteTable(Labdb, "INVOICES", INVOICES)
dbWriteTable(Labdb, "SalesOrderLine", SalesOrderLine)
dbWriteTable(Labdb, "SALESORDER", SALESORDER)
dbWriteTable(Labdb, "Product", Product)
dbWriteTable(Labdb, "Customer", Customer)
dbWriteTable(Labdb, "EmployeePhone", EmployeePhone)
dbWriteTable(Labdb, "Department", Department)
dbListTables(Labdb)
dbReadTable(Labdb, "Product")
dbGetQuery(Labdb, 'SELECT * FROM DEPARTMENT WHERE MANAGER is "null"')
dbListFields()